embeddings {
  tensor_name: "embedding:0"
  metadata_path: "D:/\347\254\224\350\256\260/pythonNoteBook/projector/projector/metadata.tsv"
  sprite {
    image_path: "D:/\347\254\224\350\256\260/pythonNoteBook/projector/data/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
